# Generated by Django 4.2.7 on 2024-10-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalues',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
    ]
